In [ ]:
#   Importamos la libreria pandas para la lectura de archivos
import pandas as pd

#   Librerias para graficar los datos
import pandas.plotting as lbPlotting

#   Libreria para crear figuras en python
import matplotlib.pyplot as plt

#
import seaborn as sns

#   abrimos el archivo con el DataSet, y especificamos que cada registro esta delimintado por ";"
df = pd.read_csv( "Laboratorio_dataset_car.csv", delimiter = ";" )

In [ ]:
#   Muestro un resumen del numero de filas y columnas del archivo (Dimensionalidad de nuestro DataSet) 
print( df.shape )

In [ ]:
#   Muestro las tres(3) primeras lineas del archivo
print( df.head(10) )

In [ ]:
#   Muestro de manera aleatoria 25 registros con la finalidad de ver un estado general de los archivos
print( df.sample(25) )

In [ ]:
#   Muestro el resumen estadistico de los datos
print( df.describe() )

In [ ]:
#   Muestro la estructura del DataSet
print( df.info() )

In [ ]:
#   Identificamos si existen valores nulos
df.isnull().sum()

In [ ]:
#   Distribucion por clases
print( df.groupby('class').size() )

In [ ]:
#   Al momento de determinar la distribucion de valores de la "clase" se identifica que los valores de los atributos 
#   no se encuentran bien distribuidos, como es el caso del atributo "Unacc", lo cual se evidencia de mejor manera 
#   mediante el siguiente grafico.

sns.countplot( x = df["class"], data = df )

In [ ]:
#   Recordemos que los algoritmos de sklearn 'no' trabajan con variables categoricas, como en este caso, 
#   por lo que es necesario transformar la informacion de valores numericos.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform( df[i] )

df.sample(10)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
X = df[df.columns[:-1]]
y = df['class']

#   Dividimos el dataset en 80% de los datos para entrenar y 20% para test   
X_train, X_validation, Y_train, Y_validation = train_test_split( X, y, test_size = 0.2, random_state = 1, shuffle = True )

In [ ]:
#   Cargamos los algoritmos
#   models = []
#   models.append( ( 'LR', LogisticRegression( solver = 'liblinear', multi_class = 'ovr' ) ) )
#   models.append( ( 'CART', DecisionTreeClassifier() ) )

In [ ]:
#   Evaluamos los modelos Logistic Regresion, y CART
#   results = []
#   names = []
#   for name, model in models:
    #   kfold = StratifiedKFold( n_splits = 10, shuffle = True, random_state = 1 )
    #   cv_results = cross_val_score( model, X_train, Y_train, cv = kfold, scoring = 'accuracy' )
    #   results.append( cv_results )
    #   names.append(name)
    #   print( '%s: %f (%f)' % ( name, cv_results.mean(), cv_results.std() ) )

In [ ]:
#   from matplotlib import pyplot
#   pyplot.boxplot( results, labels = names )
#   pyplot.title( 'Comparación de algoritmos' )
#   pyplot.show()

In [ ]:
#   Realizamos predicciones con el dataset validacion
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier()
model.fit( X_train, Y_train )
predictions = model.predict( X_validation )

In [ ]:
#   Evaluamos la exactitud (accuracy) las predicciones, en primer lugar la precision obtenida
print( accuracy_score( Y_validation, predictions ) )

In [138]:
#   Ahora elaboramos la matriz de confusion
cfn_matrix = confusion_matrix( Y_validation, predictions )
print( cfn_matrix )

[[ 71   4   2   0]
 [  1  17   0   0]
 [  2   1 242   0]
 [  0   0   0  10]]


In [ ]:
import numpy as np

class_names = [0,1]

#   Obtenemos las variables figura y ejes del gráfico (nos permite cambiar los atributos propios de cada seccion)
fig,ax = plt.subplots() 

#definimos los valores que van a tener las líneas de guía
tick_marks = np.arange( len( class_names ) )  
plt.xticks(tick_marks, class_names)

#definimos los tick marks en el gráfico
plt.yticks(tick_marks, class_names) 

# Vamos a mostrar la matriz de confusión utilizando la libreria seaborn
sns.heatmap( pd.DataFrame( cfn_matrix ), annot = True, cmap = 'Blues_r', fmt = 'g' )
ax.xaxis.set_label_position('top')

plt.tight_layout()
plt.title( 'Matriz de confusión', y = 1.1 )
plt.ylabel( 'Etiqueta Actual' )
plt.xlabel( 'Etiqueta de Predicción' )

In [ ]:
#   Informe de clasificacion
print( classification_report( Y_validation, predictions ) )