In [64]:
#   Importamos la libreria pandas para la lectura de archivos
import pandas as pd

#   Librerias para graficar los datos
import pandas.plotting as lbPlotting

#   Libreria para crear figuras en python
import matplotlib.pyplot as plt

import numpy as np

from sklearn import linear_model

from sklearn import model_selection

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sb

In [65]:
#   abrimos el archivo con el DataSet, y especificamos que cada registro esta delimintado por ";"
df = pd.read_csv( "Laboratorio_dataset_car.csv", delimiter = ";" )

In [66]:
df.describe()

Buying Maintenance Doors Person lug_boot safety  class
count    1750        1750  1750   1750     1750   1750   1750
unique      4           4     4      3        3      3      4
top     vhigh         low     2      4      big   high  unacc
freq      443         447   444    587      585    590   1215

In [67]:
#   Recordemos que los algoritmos de sklearn 'no' trabajan con variables categoricas, como en este caso, 
#   por lo que es necesario transformar la informacion de valores numericos.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform( df[i] )

df.sample(10)

Buying  Maintenance  Doors  Person  lug_boot  safety  class
647        0            0      3       1         0       1      2
685        0            2      0       2         0       0      0
1579       1            2      1       2         1       0      3
1285       2            1      2       2         0       0      3
1615       1            2      3       0         1       0      2
223        3            2      0       0         2       0      2
423        3            1      3       0         0       0      2
1148       2            2      2       0         1       1      2
315        3            2      3       1         2       0      0
890        2            3      0       1         0       1      2

In [68]:
X = np.array( df.drop( ['class'], 1 ) )
y = np.array( df['class'] )
X.shape

C:\Users\carlos.rodriguezn\AppData\Local\Temp\ipykernel_25616\170089112.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = np.array( df.drop( ['class'], 1 ) )


(1750, 6)

In [69]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [70]:
linear_model.LogisticRegression(C = 1.0, class_weight = None, dual = False, fit_intercept = True, intercept_scaling = 1, max_iter = 100, multi_class = 'ovr', n_jobs = 1,
penalty = 'l2', random_state = None, solver = 'liblinear', tol = 0.0001, verbose = 0, warm_start = False)

LogisticRegression(multi_class='ovr', n_jobs=1, solver='liblinear')

In [71]:
predictions = model.predict(X)
predictions[0:5]

array([2, 2, 2, 2, 2])

In [72]:
model.score(X, y)

0.6874285714285714

In [73]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)


In [74]:
name='Logistic Regression'
kfold = StratifiedKFold( n_splits = 10, shuffle = True, random_state = 1 )
cv_results = model_selection.cross_val_score( model, X_train, Y_train, cv = kfold, scoring = 'accuracy' )
msg= "%s: %f (%f)" % ( name, cv_results.mean(), cv_results.std() )
print( msg )

Logistic Regression: 0.665714 (0.020404)


In [75]:
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))


0.7285714285714285


In [76]:
print(confusion_matrix(Y_validation, predictions))

[[  8   0  52   6]
 [  1   0  13   0]
 [ 15   0 245   0]
 [  1   0   7   2]]


In [77]:
print(classification_report(Y_validation, predictions))

              precision    recall  f1-score   support

           0       0.32      0.12      0.18        66
           1       0.00      0.00      0.00        14
           2       0.77      0.94      0.85       260
           3       0.25      0.20      0.22        10

    accuracy                           0.73       350
   macro avg       0.34      0.32      0.31       350
weighted avg       0.64      0.73      0.67       350



C:\Users\carlos.rodriguezn\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\carlos.rodriguezn\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\carlos.rodriguezn\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera