In [ ]:
#   Importamos la libreria pandas para la lectura de archivos
import pandas as pd

#   Librerias para graficar los datos
import pandas.plotting as lbPlotting

#   Libreria para crear figuras en python
import matplotlib.pyplot as plt

import numpy as np

from sklearn import linear_model

from sklearn import model_selection

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sb




In [ ]:
#   abrimos el archivo con el DataSet, y especificamos que cada registro esta delimintado por ";"
df = pd.read_csv( "Laboratorio_dataset_car.csv", delimiter = ";" )

In [ ]:
df.describe()

In [ ]:
#   Recordemos que los algoritmos de sklearn 'no' trabajan con variables categoricas, como en este caso, 
#   por lo que es necesario transformar la informacion de valores numericos.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform( df[i] )

df.sample(10)

In [ ]:
X = np.array( df.drop( ['class'], 1 ) )
y = np.array( df['class'] )
X.shape

In [ ]:
model = linear_model.LogisticRegression()
model.fit(X,y)

In [ ]:
linear_model.LogisticRegression(C = 1.0, class_weight = None, dual = False, fit_intercept = True, intercept_scaling = 1, max_iter = 100, multi_class = 'ovr', n_jobs = 1,
penalty = 'l2', random_state = None, solver = 'liblinear', tol = 0.0001, verbose = 0, warm_start = False)

In [ ]:
predictions = model.predict(X)
#   print(predictions)[0:5]
predictions[0:5]

In [ ]:
model.score(X, y)

In [ ]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)


In [59]:
name='Logistic Regression'
kfold = StratifiedKFold( n_splits = 10, shuffle = True, random_state = 1 )
cv_results = model_selection.cross_val_score( model, X_train, Y_train, cv = kfold, scoring = 'accuracy' )
msg= "%s: %f (%f)" % ( name, cv_results.mean(), cv_results.std() )
print( msg )

Logistic Regression: 0.665714 (0.020404)


In [61]:
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))


0.7285714285714285


In [62]:
print(confusion_matrix(Y_validation, predictions))

[[  8   0  52   6]
 [  1   0  13   0]
 [ 15   0 245   0]
 [  1   0   7   2]]
