In [154]:
#   Importamos la libreria pandas para la lectura de archivos
import pandas as pd

#   Librerias para graficar los datos
import pandas.plotting as lbPlotting

#   Libreria para crear figuras en python
import matplotlib.pyplot as plt

import numpy as np

from sklearn import linear_model

from sklearn import model_selection

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sb

In [155]:
#   abrimos el archivo con el DataSet, y especificamos que cada registro esta delimintado por ";"
df = pd.read_csv( "Laboratorio_dataset_car.csv", delimiter = ";" )

In [156]:
df.describe()

Buying Maintenance Doors Person lug_boot safety  class
count    1750        1750  1750   1750     1750   1750   1750
unique      4           4     4      3        3      3      4
top     vhigh         low     2      4      big   high  unacc
freq      443         447   444    587      585    590   1215

In [157]:
#   Recordemos que los algoritmos de sklearn 'no' trabajan con variables categoricas, como en este caso, 
#   por lo que es necesario transformar la informacion de valores numericos.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform( df[i] )

df.sample(10)

Buying  Maintenance  Doors  Person  lug_boot  safety  class
381        3            1      1       2         1       1      2
918        2            3      1       1         0       2      0
555        0            0      0       0         1       2      2
1482       1            0      2       0         0       2      2
650        0            0      3       2         2       1      2
1447       1            0      0       2         0       0      3
93         3            3      3       0         0       2      2
1008       2            0      0       2         0       2      0
735        0            2      2       2         1       2      0
16         3            3      0       1         1       0      2

In [158]:
#   Dividimos el dataset en 80% de datos para entrenar y 20% de test
array = df.values
X = array[:, 0:5]
y = array[:, 6]

X_train, X_validation, Y_train, Y_validation = train_test_split( X, y, test_size = 0.2, random_state = 1, shuffle = True )

In [159]:
model = DecisionTreeClassifier()
#   Como parametros se envian las variables predictoras ( X_train ) y variables a predecir ( Y_train )
model.fit( X_train, Y_train )
predictions = model.predict( X_validation )

In [160]:
#   Evaluamos las predicciones, en primer lugar la precisión obtenida
print( accuracy_score( Y_validation, predictions ) )

0.6057142857142858


In [161]:
#   Ahora la matriz de confusion
print( confusion_matrix( Y_validation, predictions ) )

[[ 42   7  25   3]
 [  7   3   6   2]
 [ 60  15 166   4]
 [  1   7   1   1]]


In [162]:
print( classification_report( Y_validation, predictions ) )

              precision    recall  f1-score   support

           0       0.38      0.55      0.45        77
           1       0.09      0.17      0.12        18
           2       0.84      0.68      0.75       245
           3       0.10      0.10      0.10        10

    accuracy                           0.61       350
   macro avg       0.35      0.37      0.35       350
weighted avg       0.68      0.61      0.63       350

